### ISSUE TITLE
Gettin 500, I ahve Token , Channel and Username rest left to defaults any idea?

### ISSUE THREAD

**Issue by galacto** [eelzon/morgenbot#19] opened 2015-10-13 10:43 UTC
127.0.0.1 - - [13/Oct/2015 09:58:32] "POST / HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response

**Comment by Ivanknmk** [comment] 2015-10-15 01:39
@eelzon any news about this?

**Comment by Ivanknmk** [comment] 2015-10-15 03:16
@galacto I know what the issue is:

I'm sure you are pasting the token given to you [here](https://www.evernote.com/l/AKbCDB8VXG1NPKOwcPCnOGOMDReK3KAi3wg)

But that's not the one you want!

Just go [here](https://www.evernote.com/l/AKY8l49PY8lNOKSqfXc9YM0OkD9MM-zOAzo) and click on generate token...

That's all!

**Comment by eelzon** [comment] 2015-10-20 14:34
All good, @galacto and @Ivanknmk? I'm going to close this out.

**Closed by eelzon** 2015-10-20 14:34 UTC

**Comment by galacto** [comment] 2015-10-22 07:09
Sorry for delay @Ivanknmk I tried generating that token and using it but no luck 
same error
127.0.0.1 - - [22/Oct/2015 07:11:28] "POST / HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response

**Comment by galacto** [comment] 2015-10-22 07:32
I have even hardcoded the token in .py
